(*
CS2 Synatx lib...sort of...shut up!
*)
unit CS2;

interface

uses windows, sysutils, forms;

(*var
name: string;
id: string;
displayname:string;
output:string;*)

const
sLineBreak = {$IFDEF LINUX} AnsiChar(#10) {$ENDIF}
               {$IFDEF MSWINDOWS} AnsiString(#13#10) {$ENDIF};


FileHeader = 'This is autogenerated code';
name = 'name="";';
id = 'id = ;';
displayName = 'displayName[0] = "";';
addToCreative = 'addToCreative[0] = true/false;';
creativeTab = 'creativeTab = "";';
hardness = 'hardness[0] = 0;';
resistance = 'resistance[0] = 0;';
textureFileXP = 'textureFileXP[0] ="/.png"';
textureFileXN = 'textureFileXN[0] ="/.png"';
textureFileYP = 'textureFileYP[0] ="/.png"';
textureFileYN = 'textureFileYN[0] ="/.png"';
textureFileZP = 'textureFileZP[0] ="/.png"';
textureFileZN = 'textureFileZN[0] ="/.png"';

implementation

procedure Declare();
begin

end;


end.
