###############
This is autogenerated code
###############


name="";
displayName[0] = "";
addToCreative[0] = true/false;
creativeTab = "";
hardness[0] = 0;
resistance[0] = 0;
textureFileXP[0] ="/.png"
textureFileXN[0] ="/.png"
textureFileYP[0] ="/.png"
textureFileYN[0] ="/.png"
textureFileZP[0] ="/.png"
textureFileZN[0] ="/.png"